cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/',views.coupon_apply,name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('zarinpal/'),include('zarinpal.urls',namespace='zarinpal')),
    path(_('coupons/'),include('coupons.urls',namespace='coupons')),
    path("rosetta/",include('rosetta.urls')),
    path('',include('shop.urls',namespace='shop')),
)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name="orders"

urlpatterns = [
    path(_('create/'),views.order_create,name='order_create'),
    path("admin/order/<int:order_id>/",views.admin_order_detail,name="admin_order_detail"),
    path("admin/order/<int:order_id>/pdf/",views.admin_order_pdf,name="admin_order_pdf"),   
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("",views.product_list,name="product_list"),
    path("<slug:category_slug>/",views.product_list,name="product_list_by_category"),
    path("<int:id>/<slug:slug>/",views.product_detail,name="product_detail")
]

cart/forms.py
from django import forms
from django.utils.translation import override
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range (1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int,label=_("Quantity"))
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from shop.models import Product
from .forms import CartAddProductForm
from coupons.froms import CouponApplyForm
from shop.recommender import Recommender
# Create your views here.


@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products,max_results=2)
    
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item["quantity"],
            "override":True,
        })
    return render(request,'cart/detail.html',{'cart':cart,"form":coupon_apply_form,"recommended_products":recommended_products,})
    

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block title %}
  Shopping Cart 
{% endblock title %}


{% block content %}
    <h1>Your shopping cart</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
              {% with product=item.product  %}
                <tr>
                    <td>
                        <a href="{{product.get_absolute_url}}">
                            <img class="rounded-lg shadow" src="{{product.image.url}}" height="100" width="100" alt="">
                        </a>
                    </td>
                    <td>{{product.name}}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                            {{item.update_quantity_form.quantity}}
                            {{item.update_quantity_form.override}}
                            <input class="btn btn-primary" type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                            <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>{{item.price}}</td>
                    <td>{{item.total_price}}</td>
                </tr>
              {% endwith %}
            {% endfor %}
            <tr>
                <td>Total</td>
                <td colspan="4"></td>
                <td>{{cart.get_total_price}}</td>
            </tr>
            
            {% if cart.coupon %}
                <tr>
                    <td>Subtotal with {{cart.coupon.discount}}%</td>
                    <td colspan="4"></td>
                    <td class="text-success">{{cart.get_total_price_after_discount}}</td>
                </tr>
            {% endif %}
                
        </tbody>
    </table>
    <hr>
    <p>
        <a href="{% url 'shop:product_list' %}" class="btn btn-primary">Continue Shopping</a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-success">Checkout</a>
    </p>
    <p>Aooly Coupon Code:</p>
    <form action="{% url 'coupons:apply' %}" method="POST">
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Apply</button>
        {% csrf_token %}
    </form>
    <hr>
    {% if recommended_products %}
    <h3>{% trans "People who bought this also bought" %}</h3>
    {% for product in recommended_products %}
    <a href="{{product.get_absolute_url}}">
        <img src="{{product.image.url}}" alt="" width="300" height="200">
        <span>{{product.name}}</span>
    </a>
    {% endfor %}
{% endif %}  
        
            
{% endblock content %}
    