cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('zarinpal/'),include('zarinpal.urls',namespace='zarinpal')),
    path(_('coupons/'),include('coupons.urls',namespace='coupons')),
    path("rosetta/",include('rosetta.urls')),
    path('',include('shop.urls',namespace='shop')),
)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name="orders"

urlpatterns = [
    path(_('create/'),views.order_create,name='order_create'),
    path("admin/order/<int:order_id>/",views.admin_order_detail,name="admin_order_detail"),
    path("admin/order/<int:order_id>/pdf/",views.admin_order_pdf,name="admin_order_pdf"),   
]

orders/models.py
from django.db import models
from shop.models import Product
from django.utils.translation import gettext_lazy as _
# Create your models here.

class Order(models.Model):
    first_name = models.CharField(_("first name"),max_length=100)
    last_name = models.CharField(_('last name'),max_length=100)
    email = models.EmailField(_("e-mail"))
    address = models.TextField(_('address'))
    postal_code = models.CharField(_('postal code'),max_length=20)
    city = models.CharField(_("city"),max_length=100)
    created = models.DateTimeField(_("created"),auto_now_add=True)
    update = models.DateTimeField(_("update"),auto_now=True)
    paid = models.BooleanField(_("paid"),default=False)
    
    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'Order {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity
        

orders/forms.py
from django import forms
from django.forms import fields
from .models import Order

class OrderCreateform(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name',"last_name","email",'address','postal_code','city']
        

orders/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .forms import OrderCreateform
from .models import OrderItem , Order
from cart.cart import Cart
from .tasks import order_created
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required
import weasyprint
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from zarinpal.tasks import payment_completed
# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateform(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
            cart.clear()
            order_created.delay(order.id)
            # return render(request,'orders/order/created.html',{'order':order})
            request.session['order_id'] = order.id
            payment_completed.delay(order.id)
            return redirect(reverse('zarinpal:request'))
    else:
        form = OrderCreateform()
    return render(request,'orders/order/create.html',{"form":form,"cart":cart})



@staff_member_required
def admin_order_detail(request,order_id):
    order = get_object_or_404(Order,id=order_id)
    return render(request,"admin/orders/order/detail.html",{"order":order})

@staff_member_required
def admin_order_pdf(request,order_id):
    order = get_object_or_404(Order,id=order_id)
    html = render_to_string('orders/order/pdf.html',{"order":order})
    response = HttpResponse(content_type='application/pdf')
    response["Content-Disposition"] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,stylesheets=[weasyprint.CSS(
        settings.STATIC_ROOT + 'css/pdf.css'
    )])
    return response

orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Checkout</h1>
            <hr>
            <ul class="list-group">
                {% for item in cart %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <img src="{{item.product.image.url}}" class="rounded-circle img-thumbnail border-secondary" height="60" width="60" alt="">
                    {{item.product.name}} - ${{item.total_price}}
                    <span class="badge badge-primary badge-pill">{{item.quantity}}</span>
                </li>
                {% endfor %}
            </ul>
            <hr>
            
            <div class="row my-2">
                <div class="col col-lg-4 col-md-6">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_first_name">First name:</label>
                            <input type="text" class="form-control" name="first_name" maxlength="100" required id="id_first_name">
                            <label for="id_last_name">Last name:</label>
                            <input type="text" class="form-control" name="last_name" maxlength="100" required id="id_last_name">
                            <label for="id_email">Email:</label>
                            <input type="email" class="form-control" name="email" maxlength="254" required id="id_email">
                            <label for="id_address">Address:</label> 
                            <textarea name="address" class="form-control" cols="40" rows="10" required id="id_address"></textarea>
                            <label for="id_postal_code">Postal code:</label> <input type="text" name="postal_code" maxlength="20" class="form-control" required id="id_postal_code">
                            <label for="id_city">City:</label>
                            <input type="text" class="form-control" name="city" maxlength="100" required id="id_city">
                            <button type="submit" class="btn btn-primary mt-2">Order Now</button>
                      </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}


{% block content %}
    <h1>Thnak you for ordering</h1>
    your shpping id is {{order.id}}
{% endblock content %}
    

orders/templates/orders/order/pdf.html
<html>
    <body>
        <h1 class="name">Myshop</h1>
        <p>
            Invoice no {{order.id}} <br>
        <span><small>{{order.created|date:"M d Y"}}</small></span>
        </p>
        <h3>Bill to</h3>
        <p>
            {{order.first_name}} {{order.last_name}} <br>
            {{order.email}} <br>
            {{order.address}} <br>
            {{order.postal_code}}
        </p>
        <h3>Items bought</h3>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.items.all  %}
                  <tr>
                      <td>{{item.product.name}}</td>
                      <td>{{item.price}}</td>
                      <td>{{item.quantity}}</td>
                      <td>{{item.get_cost}}</td>
                  </tr>
                {% endfor %}
            </tbody>
        </table>
        <span>
            
            {% if order.paid %}
                Paid
            {% else %}
                Pending payment
            {% endif %}
                
        </span>
    </body>
</html>