cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'),include('cart.urls',namespace='cart')),
    path(_('orders/'),include('orders.urls',namespace='orders')),
    path(_('zarinpal/'),include('zarinpal.urls',namespace='zarinpal')),
    path(_('coupons/'),include('coupons.urls',namespace='coupons')),
    path("rosetta/",include('rosetta.urls')),
    path('',include('shop.urls',namespace='shop')),
)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("",views.product_list,name="product_list"),
    path("<slug:category_slug>/",views.product_list,name="product_list_by_category"),
    path("<int:id>/<slug:slug>/",views.product_detail,name="product_detail")
]

shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields
# Create your models here.

class Category(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=200,db_index=True),
        slug = models.SlugField(max_length=200,db_index=True),
    )
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    class Meta:
        #ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

class Product(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=200,db_index=True),
        slug = models.SlugField(max_length=200,db_index=True),
        description = models.TextField(blank=True),
        price = models.PositiveIntegerField()
    )
    category = models.ForeignKey(Category, related_name="products" ,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id,self.slug])

    # class Meta:
    #     ordering = ('name',)
    #     index_together = (('id','slug'),)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render , get_object_or_404
from .models import Category , Product
from cart.forms import CartAddProductForm
from .recommender import Recommender

# Create your views here.

def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,translations__language_code=language,translations__slug=category_slug)
        products = products.filter(category=category)
    context = {
            'categories':categories,
            "category":category,
            "products":products
    }
    return render(request,'shop/product/list.html',context)

def product_detail(request,id,slug):
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,id=id,
                                translations__language_code=language,
                                translations__slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    
    r = Recommender()
    recommended_products = r.suggest_products_for([product],2)
    
    context = {
        'product':product,
        'form':cart_product_form,
        'recommended_products':recommended_products,
    }
    return render(request, "shop/product/detail.html",context)

shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <title>
        {% block title %}
            {% trans "My Shop" %}
        {% endblock title %}        
    </title>
</head>
<body>
    <!-- header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'shop:product_list' %}">{% trans "My Shop" %}</a>

        <!-- select langauge -->
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}

        <div>
          <p>{% trans "language" %}</p>
          <ul>
            {% for language in languages %}
              <li><a href="/{{language.code}}/">
                {{language.name_local}}
              </a></li>
            {% endfor %}
          </ul>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'shop:product_list' %}">{% trans 'Home' %} <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="{% url 'cart:cart_detail' %}">
              <i class="fas fa-shopping-cart"></i>
              
              {% if request.session.cart %}
              <span class="badge badge-primary">{{cart|length}}</span> <span class="sr-only">(current)</span>
              
              {% blocktrans with total=cart.get_total_price %}
                <span>total price : {{total}}</span>
              {% endblocktrans %}
              
              
              {% endif %}
                
            </a>
          </div>
        </div>
      </nav>
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>